javascripts:
  todomvc:
    - 'init'
    - 'art/controller/main'
    - 'art/model/filter'
    - 'art/model/item'
    - 'art/service/db'
    - 'art/service/list_watcher'
    - 'art/view/clear_completed'
    - 'art/view/complete'
    - 'art/view/count'
    - 'art/view/edit'
    - 'art/view/filter'
    - 'art/view/filters'
    - 'art/view/footer'
    - 'art/view/item'
    - 'art/view/item_label'
    - 'art/view/list'
    - 'art/view/mark_all_complete'
    - 'art/view/main'
    - 'art/view/new'
