javascripts:
  todomvc:
    - '../init'
    - 'controller/main'
    - 'model/filter'
    - 'model/item'
    - 'service/db'
    - 'service/list_watcher'
    - 'view/clear_completed'
    - 'view/complete'
    - 'view/count'
    - 'view/edit'
    - 'view/filter'
    - 'view/filters'
    - 'view/footer'
    - 'view/item'
    - 'view/item_label'
    - 'view/list'
    - 'view/mark_all_complete'
    - 'view/main'
    - 'view/new'
